name: Build (Linux-MIGX)

on:
  push:
    paths:
      - 'vsmigx/**'
      - '.github/workflows/linux-migx.yml'
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    
    defaults:
      run:
        working-directory: vsmigx

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Ninja
      run: pip install ninja

    - name: Download VapourSynth headers
      run: |
        wget -q -O vs.zip https://github.com/vapoursynth/vapoursynth/archive/refs/tags/R57.zip
        unzip -q vs.zip
        mv vapoursynth*/ vapoursynth

    - name: Setup HIP and MIGraphX
      run: |
        wget https://repo.radeon.com/rocm/rocm.gpg.key -O - | gpg --dearmor | sudo tee /etc/apt/keyrings/rocm.gpg > /dev/null
        echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/rocm.gpg] https://repo.radeon.com/rocm/apt/6.0.2 jammy main" | sudo tee --append /etc/apt/sources.list.d/rocm.list
        echo -e 'Package: *\nPin: release o=repo.radeon.com\nPin-Priority: 600' | sudo tee /etc/apt/preferences.d/rocm-pin-600
        sudo apt update
        sudo apt install hip-runtime-amd rocm-device-libs migraphx-dev

    - name: Configure
      run: cmake -S . -B build -G Ninja -LA
        -D CMAKE_BUILD_TYPE=Release
        -D VAPOURSYNTH_INCLUDE_DIRECTORY="`pwd`/vapoursynth/include"
        -D CMAKE_CXX_COMPILER=g++-12
        -D CMAKE_CXX_FLAGS="-Wall -ffast-math -march=x86-64-v3"
        -D migraphx_DIR=/opt/rocm/lib/cmake/migraphx
        -D MIOpen_DIR=/opt/rocm/lib/cmake/miopen
        -D hip_DIR=/opt/rocm/lib/cmake/hip
        -D AMDDeviceLibs_DIR=/opt/rocm/lib/cmake/AMDDeviceLibs
        -D amd_comgr_DIR=/opt/rocm/lib/cmake/amd_comgr
        -D hsa-runtime64_DIR=/opt/rocm/lib/cmake/hsa-runtime64
        -D rocblas_DIR=/opt/rocm/lib/cmake/rocblas

    - name: Build
      run: cmake --build build --verbose

    - name: Install
      run: cmake --install build --prefix install

    - name: Prepare for upload
      run: |
        mkdir artifact
        cp -v install/lib/*.so artifact

    - name: Describe
      run: git describe --tags --long

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: VSMIGX-Linux-x64
        path: vsmigx/artifact
        overwrite: true

